[project]
name = "desktop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "slack-sdk>=3.34.0",
]

[tool.uv.workspace]
members = ["avail-js-scripts"]
